AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table creation using template.

Resources:
  device:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: devices
      AttributeDefinitions:
      - AttributeName: 'gatewayId'
        AttributeType: S
      KeySchema:
      - AttributeName: 'gatewayId'
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  telemetry:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: telemetry
      AttributeDefinitions:
      - AttributeName: 'sensorId'
        AttributeType: S
      - AttributeName: 'timestamp'
        AttributeType: S
      KeySchema:
      - AttributeName: 'sensorId'
        KeyType: HASH
      - AttributeName: 'timestamp'
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
